amazons3.settings:
  type: mapping
  label: Settings
  mapping:
    bucket:
      type: string
    region:
      type: string
    file_uri_scheme_override:
      type: boolean
    key:
      type: string
    secret:
      type: string
    cache:
      type: boolean
    cname:
      type: integer
    domain:
      type: string
    cloudfront:
      type: integer
    hostname:
      type: string
    cloudfront_keypair_id:
      type: boolean
    cloudfront_private_key:
      type: boolean
    migrate_credentials:
      type: boolean
